# Generated by Django 5.2.8 on 2025-12-13 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='recibir_newsletter',
            field=models.BooleanField(default=True, verbose_name='Recibir noticias y actualizaciones'),
        ),
        migrations.AddField(
            model_name='user',
            name='recibir_ofertas',
            field=models.BooleanField(default=True, verbose_name='Recibir ofertas y nuevos productos'),
        ),
    ]
