# Generated by Django 5.2.8 on 2025-12-13 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_carrito_updated_at_alter_pedido_estado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TarifaEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(help_text='Ciudad o Municipio destino', max_length=100, unique=True)),
                ('departamento', models.CharField(max_length=100)),
                ('precio_base', models.DecimalField(decimal_places=2, help_text='Costo envío estándar', max_digits=10)),
                ('precio_extra_producto', models.DecimalField(decimal_places=2, default=0, help_text='Costo extra por producto después de X cantidad', max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='costo_envio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='pedido',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=150, verbose_name='Quien recibe')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección exacta')),
                ('ciudad', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('referencia', models.CharField(blank=True, help_text='Apto, color casa, etc.', max_length=255, null=True)),
                ('es_principal', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='direccion_envio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.direccion'),
        ),
    ]
