# Generated by Django 5.2.8 on 2025-12-23 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_direccion_ciudad_alter_direccion_departamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
