# Generated by Django 5.2.8 on 2025-11-23 16:50

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaNoticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'Categoría de Noticia',
                'verbose_name_plural': 'Categorías de Noticias',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título del Servicio')),
                ('slug', models.SlugField(blank=True, help_text='Identificador para la URL', unique=True)),
                ('orden', models.PositiveIntegerField(default=0, help_text='Menor número aparece primero (ej: 1, 2, 3...)', verbose_name='Orden de aparición')),
                ('imagen_card', models.ImageField(upload_to='servicios/cards/', verbose_name='Imagen Pequeña')),
                ('descripcion_corta', models.TextField(verbose_name='Descripción Corta (card)')),
                ('imagen_banner', models.ImageField(blank=True, null=True, upload_to='servicios/banners/')),
                ('resumen', models.TextField(verbose_name='Summary / Resumen')),
                ('que_obtienes', django_ckeditor_5.fields.CKEditor5Field(verbose_name='What you get / Qué obtienes')),
                ('por_que_importa', models.TextField(verbose_name='Why it matters / Por qué importa')),
                ('como_funciona', django_ckeditor_5.fields.CKEditor5Field(verbose_name='How it works / Cómo funciona')),
                ('adicionales', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Optional Add-ons')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título de la Noticia')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('autor', models.CharField(default='Grupo Reina', max_length=100, verbose_name='Autor')),
                ('fecha_publicacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Publicación')),
                ('imagen_card', models.ImageField(upload_to='noticias/cards/', verbose_name='Imagen Pequeña (Card)')),
                ('imagen_banner', models.ImageField(blank=True, null=True, upload_to='noticias/banners/', verbose_name='Banner Grande')),
                ('resumen', models.TextField(max_length=400, verbose_name='Resumen corto (Intro)')),
                ('contenido', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Contenido Completo')),
                ('publicado', models.BooleanField(default=True, verbose_name='¿Publicado?')),
                ('es_destacada', models.BooleanField(default=False, verbose_name='¿Es Destacada?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='noticias', to='marketing.categorianoticia', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticias',
                'ordering': ['-fecha_publicacion'],
            },
        ),
    ]
