# Generated by Django 5.2.8 on 2025-11-23 00:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AliadoCertificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre (Ej: ICA, ISO)')),
                ('logo', models.ImageField(upload_to='aliados/', verbose_name='Logo/Sello')),
                ('url_externa', models.URLField(blank=True, null=True, verbose_name='Enlace (Opcional)')),
            ],
            options={
                'verbose_name': 'Certificación/Aliado',
                'verbose_name_plural': 'Certificaciones y Aliados',
            },
        ),
        migrations.CreateModel(
            name='CategoriaNoticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('slug', models.SlugField(help_text='Identificador URL (ej: medio-ambiente)', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título del Servicio')),
                ('descripcion_corta', models.TextField(verbose_name='Descripción Corta')),
                ('imagen', models.ImageField(upload_to='servicios/', verbose_name='Imagen Principal')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Define el orden de aparición (1, 2, 3...)')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Testimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('cargo_empresa', models.CharField(blank=True, help_text='Ej: CEO de GreenLeaf', max_length=100)),
                ('texto', models.TextField(verbose_name='Reseña')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='testimonios/')),
                ('activo', models.BooleanField(default=True, verbose_name='Mostrar en el sitio')),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('imagen_portada', models.ImageField(upload_to='noticias/')),
                ('contenido', models.TextField(help_text='Aquí va el cuerpo de la noticia')),
                ('fecha_publicacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('es_destacada', models.BooleanField(default=False, help_text='Si se marca, sale en el banner principal')),
                ('publicado', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='marketing.categorianoticia')),
            ],
            options={
                'ordering': ['-fecha_publicacion'],
            },
        ),
    ]
