# Generated by Django 5.2.8 on 2025-11-23 17:13

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaInvestigacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'Categoría de Investigación',
                'verbose_name_plural': 'Categorías de Investigaciones',
            },
        ),
        migrations.CreateModel(
            name='Investigacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título de la Investigación')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('autor', models.CharField(default='Grupo Reina', max_length=100, verbose_name='Investigador/Autor')),
                ('fecha_publicacion', models.DateField(verbose_name='Fecha de Publicación')),
                ('imagen_card', models.ImageField(upload_to='investigaciones/cards/', verbose_name='Imagen Pequeña (Card)')),
                ('imagen_banner', models.ImageField(blank=True, null=True, upload_to='investigaciones/banners/', verbose_name='Banner Grande')),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='investigaciones/documentos/', verbose_name='PDF Completo (Opcional)')),
                ('resumen', models.TextField(max_length=500, verbose_name='Resumen Ejecutivo')),
                ('contenido', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Detalles de la Investigación')),
                ('publicado', models.BooleanField(default=True)),
                ('es_destacada', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investigaciones', to='marketing.categoriainvestigacion', verbose_name='Línea de Investigación')),
            ],
            options={
                'verbose_name': 'Investigación',
                'verbose_name_plural': 'Investigaciones',
                'ordering': ['-fecha_publicacion'],
            },
        ),
    ]
