# Generated by Django 5.2.8 on 2025-11-23 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_categoriainvestigacion_investigacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre de la Certificación/Logro')),
                ('descripcion', models.TextField(blank=True, max_length=300, verbose_name='Descripción Corta')),
                ('logo', models.ImageField(upload_to='certificaciones/logos/', verbose_name='Logo o Ícono')),
                ('url_validacion', models.URLField(blank=True, null=True, verbose_name='Enlace de Verificación (URL)')),
                ('orden', models.PositiveIntegerField(default=0, help_text='1 aparece primero, 2 después...')),
                ('es_visible', models.BooleanField(default=True, verbose_name='¿Visible en la web?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Certificación / Logro',
                'verbose_name_plural': 'Certificaciones y Logros',
                'ordering': ['orden'],
            },
        ),
    ]
