# Generated by Django 5.2.8 on 2025-11-23 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_certificacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(max_length=300, verbose_name='Reseña / Opinión')),
                ('cargo_empresa', models.CharField(blank=True, max_length=100, verbose_name='Cargo / Empresa (Opcional)')),
                ('es_visible', models.BooleanField(default=False, verbose_name='¿Aprobado para mostrar?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonios', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que comenta')),
            ],
            options={
                'verbose_name': 'Testimonio / Reseña',
                'verbose_name_plural': 'Testimonios y Reseñas',
                'ordering': ['-created_at'],
            },
        ),
    ]
