# Generated by Django 5.2.8 on 2025-11-23 18:38

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0004_testimonio'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'Categoría de Blog',
                'verbose_name_plural': 'Categorías del Blog',
            },
        ),
        migrations.CreateModel(
            name='Protocolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Nombre del Cultivo (ej: Batata)')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('imagen_card', models.ImageField(upload_to='protocolos/cards/', verbose_name='Foto del Cultivo')),
                ('descripcion_tecnica', models.TextField(max_length=500, verbose_name='Descripción Técnica / Intro')),
                ('resultados', models.TextField(blank=True, max_length=300, verbose_name='Resultados Esperados')),
                ('contenido', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Pasos del Protocolo')),
                ('archivo_pdf', models.FileField(help_text="Este es el archivo que bajará el usuario al dar clic en 'Descargar Protocolo'", upload_to='protocolos/documentos/', verbose_name='PDF Descargable')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de aparición en la rejilla')),
                ('es_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Protocolo de Cultivo',
                'verbose_name_plural': 'Protocolos',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('autor', models.CharField(default='Grupo Reina', max_length=100)),
                ('fecha_publicacion', models.DateField(auto_now_add=True)),
                ('imagen_card', models.ImageField(upload_to='blog/cards/', verbose_name='Imagen Card')),
                ('imagen_banner', models.ImageField(blank=True, null=True, upload_to='blog/banners/', verbose_name='Banner')),
                ('resumen', models.TextField(max_length=400)),
                ('contenido', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Contenido del Artículo')),
                ('publicado', models.BooleanField(default=True)),
                ('es_destacado', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='marketing.categoriablog')),
            ],
            options={
                'verbose_name': 'Artículo de Blog',
                'verbose_name_plural': 'Blog',
                'ordering': ['-fecha_publicacion'],
            },
        ),
    ]
