# Generated by Django 5.2.8 on 2025-11-29 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0005_categoriablog_protocolo_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('tipo', models.CharField(choices=[('NOTICIA', 'Noticia'), ('INVESTIGACION', 'Investigación'), ('BLOG', 'Blog')], max_length=20, verbose_name='Tipo de Contenido')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'unique_together': {('slug', 'tipo')},
            },
        ),
        migrations.AlterField(
            model_name='blog',
            name='categoria',
            field=models.ForeignKey(limit_choices_to={'tipo': 'BLOG'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='marketing.categoria'),
        ),
        migrations.AlterField(
            model_name='investigacion',
            name='categoria',
            field=models.ForeignKey(limit_choices_to={'tipo': 'INVESTIGACION'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investigaciones', to='marketing.categoria', verbose_name='Línea de Investigación'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='categoria',
            field=models.ForeignKey(limit_choices_to={'tipo': 'NOTICIA'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='noticias', to='marketing.categoria', verbose_name='Categoría'),
        ),
        migrations.DeleteModel(
            name='CategoriaBlog',
        ),
        migrations.DeleteModel(
            name='CategoriaInvestigacion',
        ),
        migrations.DeleteModel(
            name='CategoriaNoticia',
        ),
    ]
