# Generated by Django 5.2.8 on 2025-11-29 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0006_categoria_alter_blog_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='tipo',
            field=models.CharField(choices=[('NOTICIA', 'Noticia'), ('INVESTIGACION', 'Investigación'), ('BLOG', 'Blog'), ('PRODUCTO', 'Producto')], max_length=20, verbose_name='Tipo de Contenido'),
        ),
    ]
