# Generated by Django 5.2.8 on 2025-12-20 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0007_alter_categoria_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocolo',
            name='archivo_pdf',
            field=models.FileField(blank=True, help_text="Este es el archivo que bajará el usuario al dar clic en 'Descargar Protocolo'", null=True, upload_to='protocolos/documentos/', verbose_name='PDF Descargable'),
        ),
        migrations.AlterField(
            model_name='protocolo',
            name='imagen_card',
            field=models.ImageField(blank=True, null=True, upload_to='protocolos/cards/', verbose_name='Foto del Cultivo'),
        ),
    ]
