# Generated by Django 5.2.8 on 2025-12-22 00:14

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0008_alter_protocolo_archivo_pdf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='autor',
            field=models.CharField(blank=True, default='Grupo Reina', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='contenido',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Contenido del Artículo'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='imagen_card',
            field=models.ImageField(blank=True, null=True, upload_to='blog/cards/', verbose_name='Imagen Card'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='titulo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='certificacion',
            name='descripcion',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Descripción Corta'),
        ),
        migrations.AlterField(
            model_name='certificacion',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='certificaciones/logos/', verbose_name='Logo o Ícono'),
        ),
        migrations.AlterField(
            model_name='certificacion',
            name='nombre',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre de la Certificación/Logro'),
        ),
        migrations.AlterField(
            model_name='certificacion',
            name='orden',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='1 aparece primero, 2 después...', null=True),
        ),
        migrations.AlterField(
            model_name='investigacion',
            name='autor',
            field=models.CharField(blank=True, default='Grupo Reina', max_length=100, null=True, verbose_name='Investigador/Autor'),
        ),
        migrations.AlterField(
            model_name='investigacion',
            name='contenido',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Detalles de la Investigación'),
        ),
        migrations.AlterField(
            model_name='investigacion',
            name='fecha_publicacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Publicación'),
        ),
        migrations.AlterField(
            model_name='investigacion',
            name='imagen_card',
            field=models.ImageField(blank=True, null=True, upload_to='investigaciones/cards/', verbose_name='Imagen Pequeña (Card)'),
        ),
        migrations.AlterField(
            model_name='investigacion',
            name='resumen',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Resumen Ejecutivo'),
        ),
        migrations.AlterField(
            model_name='investigacion',
            name='titulo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Título de la Investigación'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='autor',
            field=models.CharField(blank=True, default='Grupo Reina', max_length=100, null=True, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='contenido',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Contenido Completo'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='es_destacada',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='¿Es Destacada?'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='fecha_publicacion',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Fecha de Publicación'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='imagen_card',
            field=models.ImageField(blank=True, null=True, upload_to='noticias/cards/', verbose_name='Imagen Pequeña (Card)'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='publicado',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='¿Publicado?'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='resumen',
            field=models.TextField(blank=True, max_length=400, null=True, verbose_name='Resumen corto (Intro)'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='titulo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Título de la Noticia'),
        ),
        migrations.AlterField(
            model_name='protocolo',
            name='contenido',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Pasos del Protocolo'),
        ),
        migrations.AlterField(
            model_name='protocolo',
            name='descripcion_tecnica',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Descripción Técnica / Intro'),
        ),
        migrations.AlterField(
            model_name='protocolo',
            name='resultados',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Resultados Esperados'),
        ),
        migrations.AlterField(
            model_name='protocolo',
            name='titulo',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre del Cultivo (ej: Batata)'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='como_funciona',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='How it works / Cómo funciona'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='descripcion_corta',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción Corta (card)'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='imagen_card',
            field=models.ImageField(blank=True, null=True, upload_to='servicios/cards/', verbose_name='Imagen Pequeña'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='por_que_importa',
            field=models.TextField(blank=True, null=True, verbose_name='Why it matters / Por qué importa'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='que_obtienes',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='What you get / Qué obtienes'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='resumen',
            field=models.TextField(blank=True, null=True, verbose_name='Summary / Resumen'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='titulo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Título del Servicio'),
        ),
        migrations.AlterField(
            model_name='testimonio',
            name='cargo_empresa',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo / Empresa (Opcional)'),
        ),
        migrations.AlterField(
            model_name='testimonio',
            name='contenido',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Reseña / Opinión'),
        ),
        migrations.AlterField(
            model_name='testimonio',
            name='es_visible',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='¿Aprobado para mostrar?'),
        ),
    ]
