# Generated by Django 5.2.8 on 2025-12-23 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0009_alter_blog_autor_alter_blog_contenido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='certificacion',
            name='nombre',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre de la Certificación/Logro'),
        ),
        migrations.AlterField(
            model_name='investigacion',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='protocolo',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='protocolo',
            name='titulo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre del Cultivo (ej: Batata)'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='slug',
            field=models.SlugField(blank=True, help_text='Identificador para la URL', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='titulo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Título del Servicio'),
        ),
    ]
